// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AuthorService from "./authorservice.js";
import * as PostService from "./postservice.js";
export {
    AuthorService,
    PostService
};

export * from "./models.js";
