// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export const Author = models$0.Author;

/**
 * @typedef {models$0.Author} Author
 */

export const Comment = models$0.Comment;

/**
 * @typedef {models$0.Comment} Comment
 */

export const Post = models$0.Post;

/**
 * @typedef {models$0.Post} Post
 */

export const PostType = models$0.PostType;

/**
 * @typedef {models$0.PostType} PostType
 */
