// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export const Customer = models$0.Customer;
export type Customer = models$0.Customer;

export const Order = models$0.Order;
export type Order = models$0.Order;

export const PrepTask = models$0.PrepTask;
export type PrepTask = models$0.PrepTask;

export const ProductType = models$0.ProductType;
export type ProductType = models$0.ProductType;

export const Shift = models$0.Shift;
export type Shift = models$0.Shift;

export const Task = models$0.Task;
export type Task = models$0.Task;

export const TeamTask = models$0.TeamTask;
export type TeamTask = models$0.TeamTask;

export const TeamType = models$0.TeamType;
export type TeamType = models$0.TeamType;

export const WorkArea = models$0.WorkArea;
export type WorkArea = models$0.WorkArea;

export const Worker = models$0.Worker;
export type Worker = models$0.Worker;

export const Workshop = models$0.Workshop;
export type Workshop = models$0.Workshop;
