// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"app/internal/models"
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&models.TeamType{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.TeamType{}) fail: %s", err)
	}
}

func Test_teamTypeQuery(t *testing.T) {
	teamType := newTeamType(_gen_test_db)
	teamType = *teamType.As(teamType.TableName())
	_do := teamType.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(teamType.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <team_types> fail:", err)
		return
	}

	_, ok := teamType.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from teamType success")
	}

	err = _do.Create(&models.TeamType{})
	if err != nil {
		t.Error("create item in table <team_types> fail:", err)
	}

	err = _do.Save(&models.TeamType{})
	if err != nil {
		t.Error("create item in table <team_types> fail:", err)
	}

	err = _do.CreateInBatches([]*models.TeamType{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <team_types> fail:", err)
	}

	_, err = _do.Select(teamType.ALL).Take()
	if err != nil {
		t.Error("Take() on table <team_types> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <team_types> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <team_types> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <team_types> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.TeamType{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <team_types> fail:", err)
	}

	_, err = _do.Select(teamType.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <team_types> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <team_types> fail:", err)
	}

	_, err = _do.Select(teamType.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <team_types> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <team_types> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <team_types> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <team_types> fail:", err)
	}

	_, err = _do.ScanByPage(&models.TeamType{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <team_types> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <team_types> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <team_types> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <team_types> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <team_types> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <team_types> fail:", err)
	}
}
