// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"app/internal/models"
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&models.Worker{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.Worker{}) fail: %s", err)
	}
}

func Test_workerQuery(t *testing.T) {
	worker := newWorker(_gen_test_db)
	worker = *worker.As(worker.TableName())
	_do := worker.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(worker.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <workers> fail:", err)
		return
	}

	_, ok := worker.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from worker success")
	}

	err = _do.Create(&models.Worker{})
	if err != nil {
		t.Error("create item in table <workers> fail:", err)
	}

	err = _do.Save(&models.Worker{})
	if err != nil {
		t.Error("create item in table <workers> fail:", err)
	}

	err = _do.CreateInBatches([]*models.Worker{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <workers> fail:", err)
	}

	_, err = _do.Select(worker.ALL).Take()
	if err != nil {
		t.Error("Take() on table <workers> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <workers> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <workers> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <workers> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.Worker{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <workers> fail:", err)
	}

	_, err = _do.Select(worker.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <workers> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <workers> fail:", err)
	}

	_, err = _do.Select(worker.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <workers> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <workers> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <workers> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <workers> fail:", err)
	}

	_, err = _do.ScanByPage(&models.Worker{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <workers> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <workers> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <workers> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <workers> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <workers> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <workers> fail:", err)
	}
}
