// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DryModeService from "./drymodeservice.js";
import * as DryReportService from "./dryreportservice.js";
import * as ExcelModule from "./excelmodule.js";
import * as ExporterService from "./exporterservice.js";
import * as PostavService from "./postavservice.js";
import * as ReceiverService from "./receiverservice.js";
import * as ReportService from "./reportservice.js";
import * as SushkaResultService from "./sushkaresultservice.js";
import * as WoodSpecService from "./woodspecservice.js";
import * as WoodSpecTypeService from "./woodspectypeservice.js";
import * as WorkResultService from "./workresultservice.js";
export {
    DryModeService,
    DryReportService,
    ExcelModule,
    ExporterService,
    PostavService,
    ReceiverService,
    ReportService,
    SushkaResultService,
    WoodSpecService,
    WoodSpecTypeService,
    WorkResultService
};

export * from "./models.js";
